#!/bin/bash

original_brightness=`brightness get`

function reset_brightness {
    brightness $original_brightness 
}

trap reset_brightness EXIT
sleeptime=0.25
while sleep $sleeptime; do brightness 10%; sleep $sleeptime; brightness 100%; done


