#!/bin/bash

a_time=30min
b_time=5min

date +%R:%S
echo Procrastinadoro: do stuff for $a_time
notify-send -u low -t 3000 Procrastinadoro "You have $a_time"
countdown $a_time
notify-send -u critical Procrastinadoro "Done with that"
date +%R:%S
echo Procrastinadoro: $b_time break
notify-send -u low -t 3000 Procrastinadoro "You have $b_time"
countdown $b_time
notify-send -u critical Procrastinadoro "Done with this"
read
date +%R:%S
echo Procrastinadoro: delayed break or cancel
countdown $b_time
notify-send -u critical Procrastinadoro "Finally done"

